# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'pipelines-javascript-docker'
  phpVersion: 7.4

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'SecurityAPI.pem'
- script:
    sudo ls
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'

- script: php -r "file_exists('.env') || copy('.env.example', '.env');"
  displayName: 'copy .env'

- script: php artisan key:generate --ansi
  displayName: 'artisan key:generate'

- script: ./vendor/bin/phpunit
  displayName: 'Run tests with phpunit'

- script: php artisan route:list
  displayName: 'route:list'

- script: npm install
  displayName: 'npm install'

- script: npx mix
  displayName: 'npx mix'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(system.defaultWorkingDirectory)'
    includeRootFolder: false
