version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
      - LARAVEL_SAIL=1
      - XDEBUG_MODE=${SAIL_XDEBUG_MODE:-off}
      - XDEBUG_CONFIG=${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT:-80}:80"
    networks:
      backend:
        aliases:
          - laravel-app

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
      - ./run/dump/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    links:
      - "db:database"
    ports:
      - "81:80"
networks:
  backend:
    name: backend-network
